version: '3.9'

services:
  db:
    image: 'postgres'
    environment:
      POSTGRES_PASSWORD: 'root'
      POSTGRES_USER: 'postgres'
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data
volumes:
  data: